// Code generated by counterfeiter. DO NOT EDIT.
package internalfakes

import (
	"image"
	"sync"

	"github.com/petewall/eink-radiator-image-source-text/internal"
)

type FakeContextMaker struct {
	Stub        func(image.Image) internal.Context
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 image.Image
	}
	returns struct {
		result1 internal.Context
	}
	returnsOnCall map[int]struct {
		result1 internal.Context
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeContextMaker) Spy(arg1 image.Image) internal.Context {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 image.Image
	}{arg1})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("ContextMaker", []interface{}{arg1})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return returns.result1
}

func (fake *FakeContextMaker) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeContextMaker) Calls(stub func(image.Image) internal.Context) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeContextMaker) ArgsForCall(i int) image.Image {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1
}

func (fake *FakeContextMaker) Returns(result1 internal.Context) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 internal.Context
	}{result1}
}

func (fake *FakeContextMaker) ReturnsOnCall(i int, result1 internal.Context) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 internal.Context
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 internal.Context
	}{result1}
}

func (fake *FakeContextMaker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeContextMaker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ internal.ContextMaker = new(FakeContextMaker).Spy
